### ISSUE TITLE
spatial spec example problematic

### ISSUE THREAD

**Issue by sbmlsecretary** [sbmlteam/sbml-specifications#362]
The example at `spatial/specification/examples/sampledfield_asnt.xml` is problematic, in that 

- the id`'imgvals` is used twice for a parameter and a sample field
- the initial assignment uses the id of the geometry `img`,  rather than the sample field (or parameter) `imgvals`

Reported by: fbergmann

Original Ticket: [sbml/sbml-specifications//364](https://sourceforge.net/p/sbml/sbml-specifications//364)

**Comment by luciansmith** [comment]
It looks like this has been fixed:

* The initial assignment now uses 'imgvals' properly.
* Using the same ID for the parameter and the sampled field is intentional:  the sampled field id is in the spatial namespace, and the parameter is in the core namespace.  This is the whole point of the spatialSymbolReference: to connect the two namespaces.

**Comment by luciansmith** [comment]
(Closing, but feel free to re-open @fbergmann if you feel it needs to be addressed more.)
