### ISSUE TITLE
Spatial validation rule 21350 too stringent

### ISSUE THREAD

**Issue by luciansmith** [sbmlteam/sbml-specifications#392]
Rule 21350 only applies when the mapped compartments are the same dimensions, not if they are different (cf https://github.com/sbmlteam/libsbml/issues/275).  

The new rule should be:

"The value of the attribute \token{spatial:unitSize} on a \CompartmentMapping must have a value between 0 and 1, inclusive, when the dimensions of the referenced compartments have the same dimensions."

**Comment by luciansmith** [comment]
I'm inclined to make this change before submitting to JIB.  @fbergmann , opinions?

**Comment by fbergmann** [comment]
If we change it, since really it is a best guidance rule, we additionally should change it from a *must* to a *should*. This is also what came out in discussions with @jcschaff. I'm happy for it to change in time for the JIB thing. it does not change anything form the spec, other than this validation rule.

**Comment by luciansmith** [comment]
Sounds good to me!  Changed from 'must' to 'should', and downgraded it to  a warning instead of an error.
